**Tweets**

In [ ]:
import pandas as pd
dftweet =pd.read_json("drive/MyDrive/Colab Notebooks/tweet1.json")

In [ ]:
#lo mismo pero radom
import ast
import pandas as pd

def parse_public_metrics(x):
    if isinstance(x, dict):
        return x
    if isinstance(x, str) and x.strip() != "":
        return ast.literal_eval(x)
    return {}

dftweet["public_metrics"] = dftweet["public_metrics"].apply(parse_public_metrics)
metrics_dftweet = dftweet["public_metrics"].apply(pd.Series)
dftweet = pd.concat([dftweet.drop(columns=["public_metrics"]), metrics_dftweet], axis=1)
dftweet["entities"] = dftweet["entities"].apply(parse_public_metrics)
entities_dftweet = dftweet["entities"].apply(pd.Series)
dftweet = pd.concat([dftweet.drop(columns=["entities"]), entities_dftweet], axis=1)

In [ ]:
dftweet.tail()

,attachments,author_id,context_annotations,conversation_id,created_at,geo,id,in_reply_to_user_id,lang,possibly_sensitive,...,like_count,quote_count,hashtags,symbols,user_mentions,urls,media,mentions,annotations,cashtags
1299995,None,1455144704446709761,None,1455864074445668356,2021-11-03 11:46:58+00:00,None,t1455864074445668356,NaN,en,False,...,0.0,NaN,"[{'text': 'globalsteel', 'indices': [18, 30]}]",[],"[{'screen_name': 'KWitecka', 'name': 'Wido K W...",[],NaN,NaN,NaN,NaN
1299996,None,1466337198,None,351887415100719106,2013-07-02 02:17:52+00:00,None,t351887415100719106,NaN,en,False,...,0.0,NaN,[],[],"[{'screen_name': 'nasa_eo', 'name': 'NASA_EO',...",[],"[{'id': 348442960968437761, 'id_str': '3484429...",NaN,NaN,NaN
1299997,None,714772683884376065,None,896411729814532100,2017-08-12 16:43:05+00:00,None,t896411729814532100,NaN,en,False,...,2045.0,NaN,"[{'text': 'PrasoonJoshi', 'indices': [10, 23]}]",[],"[{'screen_name': 'smritiirani', 'name': 'Smrit...",[],NaN,NaN,NaN,NaN
1299998,None,817679968025055232,None,1496005216508039170,2022-02-22 06:13:32+00:00,None,t1496005216508039170,NaN,en,False,...,0.0,NaN,"[{'text': 'AI', 'indices': [36, 39]}, {'text':...",[],"[{'screen_name': 'jblefevre60', 'name': 'Jean-...",[],NaN,NaN,NaN,NaN
1299999,None,1289721716537569280,None,1499498286134095874,2022-03-03 21:33:45+00:00,None,t1499498286134095874,1.282705e+18,en,False,...,1.0,NaN,[],[],"[{'screen_name': 'iamhaunted13', 'name': 'nani...",[],NaN,NaN,NaN,NaN

In [ ]:
dftweet['reply_count'].notnull().sum()

np.int64(106764)

In [ ]:
dftweet.columns

Index(['attachments', 'author_id', 'context_annotations', 'conversation_id',
       'created_at', 'geo', 'id', 'in_reply_to_user_id', 'lang',
       'possibly_sensitive', 'referenced_tweets', 'reply_settings', 'source',
       'text', 'withheld', 'retweet_count', 'reply_count', 'like_count',
       'quote_count', 'hashtags', 'symbols', 'user_mentions', 'urls', 'media',
       'mentions', 'annotations', 'cashtags'],
      dtype='object')

In [ ]:
dftweet.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1300000 entries, 0 to 1299999
Data columns (total 27 columns):
 #   Column               Non-Null Count    Dtype
---  ------               --------------    -----
 0   attachments          27734 non-null    object
 1   author_id            1300000 non-null  int64
 2   context_annotations  106764 non-null   object
 3   conversation_id      1300000 non-null  int64
 4   created_at           1300000 non-null  datetime64[ns, UTC]
 5   geo                  3496 non-null     object
 6   id                   1300000 non-null  object
 7   in_reply_to_user_id  342995 non-null   float64
 8   lang                 1300000 non-null  object
 9   possibly_sensitive   1300000 non-null  bool
 10  referenced_tweets    62235 non-null    object
 11  reply_settings       106764 non-null   object
 12  source               1300000 non-null  object
 13  text                 1300000 non-null  object
 14  withheld             33 non-null       object
 15  retweet_count        1300000 non-null  float64
 16  reply_count          106764 non-null   float64
 17  like_count           1300000 non-null  float64
 18  quote_count          106764 non-null   float64
 19  hashtags             1220361 non-null  object
 20  symbols              1193236 non-null  object
 21  user_mentions        1193236 non-null  object
 22  urls                 1249665 non-null  object
 23  media                262977 non-null   object
 24  mentions             59221 non-null    object
 25  annotations          36430 non-null    object
 26  cashtags             297 non-null      object
dtypes: bool(1), datetime64[ns, UTC](1), float64(5), int64(2), object(18)
memory usage: 269.0+ MB

In [ ]:
dftweet.describe()

,author_id,conversation_id,in_reply_to_user_id,retweet_count,reply_count,like_count,quote_count
count,1.300000e+06,1.300000e+06,3.429950e+05,1.300000e+06,106764.000000,1.300000e+06,106764.000000
mean,3.504597e+17,1.452489e+18,4.320629e+17,5.844501e+02,6.868739,1.285963e+02,2.965606
std,5.341667e+17,1.564479e+17,5.761284e+17,1.065743e+04,251.034597,3.372377e+03,182.382048
min,1.200000e+01,5.950311e+06,1.200000e+01,0.000000e+00,0.000000,0.000000e+00,0.000000
25%,1.050416e+08,1.485927e+18,1.298507e+08,0.000000e+00,0.000000,0.000000e+00,0.000000
50%,9.181018e+08,1.496218e+18,1.580549e+09,1.000000e+00,0.000000,0.000000e+00,0.000000
75%,8.791343e+17,1.498717e+18,1.038120e+18,1.100000e+01,0.000000,3.000000e+00,0.000000
max,1.499405e+18,1.503399e+18,1.502940e+18,3.816974e+06,56681.000000,1.201112e+06,39729.000000

In [ ]:
dftweet.drop(columns=['attachments', 'context_annotations', 'conversation_id', 'geo','lang','possibly_sensitive', 'reply_settings', 'source', 'withheld','quote_count','symbols','text','in_reply_to_user_id','referenced_tweets','user_mentions'], inplace=True)

In [ ]:
dftweet

In [ ]:
dftweet.drop(columns=['mentions','annotations','cashtags'], inplace=True)

In [ ]:
for col in ["hashtags", "urls", "media"]:
    dftweet[f"has_{col}"] = dftweet[col].str.len().fillna(0).gt(0).astype(int)

In [ ]:
dftweet.drop(columns=['hashtags','urls','media'], inplace=True)

In [ ]:
df_user = dftweet.groupby("author_id").agg({
    "retweet_count": "sum",
    "reply_count": "sum",
    "like_count": "sum",
    "has_hashtags": "sum",
    "has_urls": "sum",
    "has_media": "sum"
})

In [ ]:
df_user

,retweet_count,reply_count,like_count,has_hashtags,has_urls,has_media
author_id,,,,,,
12,105233.0,0.0,482314.0,0,5,5
47,0.0,0.0,1.0,0,0,0
58,4.0,0.0,18.0,0,1,0
59,9.0,0.0,60.0,0,1,3
76,69.0,0.0,1562.0,2,2,4
...,...,...,...,...,...,...
1495613475963682818,2430.0,0.0,0.0,1,0,0
1495762038316220417,0.0,0.0,0.0,2,1,0
1495763319499915267,0.0,0.0,1.0,0,3,0
1495782767342362626,73.0,0.0,0.0,3,0,0
1495866073043906562,3.0,0.0,0.0,5,0,5

In [ ]:
df_user[df_user["id"] == 1466337198]

,id,retweet_count,reply_count,like_count,has_hashtags,has_urls,has_media
138601,1466337198,377.0,0.0,0.0,0,0,1

In [ ]:
df_user = df_user.reset_index()
df_user.rename(columns={"author_id": "id"}, inplace=True)

In [ ]:
df_user.shape

(270293, 7)

In [ ]:
df_user.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270293 entries, 0 to 270292
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             270293 non-null  int64
 1   retweet_count  270293 non-null  float64
 2   reply_count    270293 non-null  float64
 3   like_count     270293 non-null  float64
 4   has_hashtags   270293 non-null  int64
 5   has_urls       270293 non-null  int64
 6   has_media      270293 non-null  int64
dtypes: float64(3), int64(4)
memory usage: 14.4 MB

In [ ]:
df_user.to_json("tweet2final.json")

In [ ]:
import pandas as pd
dftweet1 =pd.read_json("tweet1final.json")
dftweet2=pd.read_json("tweet2final.json")
dftweet_final=pd.concat([dftweet1,dftweet2])

In [ ]:
dftweet_final.tail()

,id,retweet_count,reply_count,like_count,has_hashtags,has_urls,has_media
270288,1495613475963682818,2430,0,0,1,0,0
270289,1495762038316220417,0,0,0,2,1,0
270290,1495763319499915267,0,0,1,0,3,0
270291,1495782767342362626,73,0,0,3,0,0
270292,1495866073043906562,3,0,0,5,0,5

In [ ]:
dftweet_final.shape

(527113, 7)

In [ ]:
dftweet_final["id"] = dftweet_final["id"].astype("object")
dftweet_final["id"] = "u" + dftweet_final["id"].astype(str)

In [ ]:
dftweet_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 527113 entries, 0 to 270292
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   id             527113 non-null  object
 1   retweet_count  527113 non-null  int64
 2   reply_count    527113 non-null  int64
 3   like_count     527113 non-null  int64
 4   has_hashtags   527113 non-null  int64
 5   has_urls       527113 non-null  int64
 6   has_media      527113 non-null  int64
dtypes: int64(6), object(1)
memory usage: 32.2+ MB

**Users**

In [ ]:
!pip install ijson

Requirement already satisfied: ijson in /usr/local/lib/python3.12/dist-packages (3.4.0.post0)

In [ ]:
#json muy pesado ijson para poedr seleccionar alas filas
import ijson

with open("drive/MyDrive/Colab Notebooks/user.json", "rb") as f:
    objects = ijson.items(f, "item")
    first_user = next(objects)

print(first_user.keys())

dict_keys(['created_at', 'description', 'entities', 'id', 'location', 'name', 'pinned_tweet_id', 'profile_image_url', 'protected', 'public_metrics', 'url', 'username', 'verified', 'withheld'])

In [ ]:
#lo mismo pero random
import ijson
import random

k = 900000
users = []

with open("drive/MyDrive/Colab Notebooks/user.json", "rb") as f:
    for i, user in enumerate(ijson.items(f, "item")):
        if i < k:
            users.append(user)
        else:
            j = random.randint(0, i)
            if j < k:
                users[j] = user

len(users)
dfrand = pd.DataFrame(users)

In [ ]:
#cargamos los labels
label =pd.read_csv("drive/MyDrive/Colab Notebooks/label.csv")

In [ ]:
#lo mismo pero radom
import ast
import pandas as pd

def parse_public_metrics(x):
    if isinstance(x, dict):
        return x
    if isinstance(x, str) and x.strip() != "":
        return ast.literal_eval(x)
    return {}

dfrand["public_metrics"] = dfrand["public_metrics"].apply(parse_public_metrics)
metrics_dfrand = dfrand["public_metrics"].apply(pd.Series)
dfrand = pd.concat([dfrand.drop(columns=["public_metrics"]), metrics_dfrand], axis=1)
df2rand = pd.merge(dfrand, label, on='id', how='left')

In [ ]:
df2rand.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 900000 entries, 0 to 899999
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   created_at         900000 non-null  object
 1   description        900000 non-null  object
 2   entities           567771 non-null  object
 3   id                 900000 non-null  object
 4   location           637663 non-null  object
 5   name               900000 non-null  object
 6   pinned_tweet_id    350894 non-null  float64
 7   profile_image_url  900000 non-null  object
 8   protected          900000 non-null  bool
 9   url                900000 non-null  object
 10  username           900000 non-null  object
 11  verified           900000 non-null  bool
 12  withheld           51 non-null      object
 13  followers_count    900000 non-null  int64
 14  following_count    900000 non-null  int64
 15  tweet_count        900000 non-null  int64
 16  listed_count       900000 non-null  int64
 17  label              900000 non-null  object
dtypes: bool(2), float64(1), int64(4), object(11)
memory usage: 111.6+ MB

In [ ]:
df_final = pd.merge(df2rand,dftweet_final ,on='id', how='left')

NameError: name 'pd' is not defined

In [ ]:
df_final

,created_at,description,entities,id,location,name,pinned_tweet_id,profile_image_url,protected,url,...,following_count,tweet_count,listed_count,label,retweet_count,reply_count,like_count,has_hashtags,has_urls,has_media
0,2020-01-16 02:02:55+00:00,Theoretical Computer Scientist. See also https...,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u1217628182611927040,"Cambridge, MA",Boaz Barak,NaN,https://pbs.twimg.com/profile_images/125226236...,False,https://t.co/BoMip9FF17,...,215,3098,69,human,66,0,0,0,0,0
1,2020-01-16 02:02:55+00:00,Theoretical Computer Scientist. See also https...,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u1217628182611927040,"Cambridge, MA",Boaz Barak,NaN,https://pbs.twimg.com/profile_images/125226236...,False,https://t.co/BoMip9FF17,...,215,3098,69,human,174,0,632,1,5,1
3,2012-02-21 19:25:01+00:00,"Husband, dad, poet, movie blogger, sports fan,...","{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u499091808,None,Dell on Movies,1.477858e+18,https://pbs.twimg.com/profile_images/130517574...,False,https://t.co/0C9nCXz8om,...,2690,25106,64,human,123,0,1,0,2,1
7,2020-07-23 16:49:48+00:00,her şeye rağmen yaşıyoruz,None,u1286342710157291520,المريخ,عبدالله,NaN,https://pbs.twimg.com/profile_images/131539468...,False,,...,813,102,8,human,48,0,0,0,0,0
9,2008-06-23 20:59:59+00:00,"Director, Knowledge Ecology International, an ...","{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u15211869,"ÜT: 38.911326,-77.04508",James Love,1.335259e+18,https://pbs.twimg.com/profile_images/126138453...,False,https://t.co/mcNZxOR7gv,...,2166,57397,383,human,3,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976346,2021-12-24 15:33:29+00:00,,None,u1474402819801337862,None,Bob,NaN,https://abs.twimg.com/sticky/default_profile_i...,False,,...,119,1221,0,bot,431,0,0,1,1,7
976347,2017-05-25 07:50:58+00:00,,None,u867649175911100416,None,Tati Jewelry,NaN,https://pbs.twimg.com/profile_images/867651664...,False,,...,522,396779,26,human,236,0,0,1,1,1
976348,2012-11-30 12:29:41+00:00,todos los dias on-line las 24hs por todos esto...,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u980374429,Ciudad Autónoma de Buenos Aire,TwitRadioo,9.012569e+17,https://pbs.twimg.com/profile_images/901249265...,False,https://t.co/KgoPxOXrUk,...,424,98231,18,human,6,0,1,1,2,0
976349,2018-12-13 12:35:45+00:00,"Perpetual student of bioanalytical sciences, l...","{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u1073194762407165952,None,SchejbalJan,NaN,https://pbs.twimg.com/profile_images/107319735...,False,https://t.co/S6e1ewGv2M,...,319,1048,2,human,5,0,8,0,1,0
976350,2011-03-16 19:30:29+00:00,سناب خبر وعلم لنشر الوظائف الشاغرة والأخبار ال...,"{'description': {'urls': [{'start': 60, 'end':...",u267342787,المملكة العربية السعودية,خبر و عِلم,NaN,https://pbs.twimg.com/profile_images/148453887...,False,,...,130,4946,13,human,0,0,1,5,3,9

In [ ]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Index: 474546 entries, 0 to 976350
Data columns (total 24 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   created_at         474546 non-null  datetime64[ns, UTC]
 1   description        474546 non-null  object
 2   entities           354291 non-null  object
 3   id                 474546 non-null  object
 4   location           368588 non-null  object
 5   name               474546 non-null  object
 6   pinned_tweet_id    240304 non-null  float64
 7   profile_image_url  474546 non-null  object
 8   protected          474546 non-null  bool
 9   url                474546 non-null  object
 10  username           474546 non-null  object
 11  verified           474546 non-null  bool
 12  withheld           44 non-null      object
 13  followers_count    474546 non-null  int64
 14  following_count    474546 non-null  int64
 15  tweet_count        474546 non-null  int64
 16  listed_count       474546 non-null  int64
 17  label              474546 non-null  object
 18  retweet_count      474546 non-null  int64
 19  reply_count        474546 non-null  int64
 20  like_count         474546 non-null  int64
 21  has_hashtags       474546 non-null  int64
 22  has_urls           474546 non-null  int64
 23  has_media          474546 non-null  int64
dtypes: bool(2), datetime64[ns, UTC](1), float64(1), int64(10), object(10)
memory usage: 84.2+ MB

In [ ]:
df_final['retweet_count'].notnull().sum()

np.int64(474546)

In [ ]:
df_final= df_final.dropna(subset=["retweet_count"])

In [ ]:
df_final.to_json("df_final.json")



```
# This is formatted as code
```

# Aqui empieza

In [ ]:
import numpy as np

In [ ]:
import pandas as pd
df_final =pd.read_json("drive/MyDrive/TFM/df_final.json")

In [ ]:
#agregando una columna con el days variance

df_final["created_at"] = pd.to_datetime(df_final["created_at"])
df_final["Cutoverdate"] = pd.to_datetime("2022-03-16", utc=True) # Make Cutoverdate timezone-aware (UTC)
df_final["account_age_day"]=(df_final["Cutoverdate"]-df_final["created_at"]).dt.days
df_final["followers_following_ratio"]=(df_final["followers_count"]/(df_final["following_count"]+1))
df_final["tweets_per_day"]=(df_final["tweet_count"]/df_final["account_age_day"])
df_final["description_length"] = df_final["description"].str.len().fillna(0)
df_final["url_ratio"]=(df_final["has_urls"]/(df_final["tweet_count"]+1))
df_final["hashtag_ratio"]=(df_final["has_hashtags"]/(df_final["tweet_count"]+1))
df_final["media_ratio"]=(df_final["has_media"]/(df_final["tweet_count"]+1))
df_final["engagement_ratio"]=(    df_final["like_count"] +    df_final["retweet_count"] +    df_final["reply_count"]) / (df_final["followers_count"] + 1)
df_final["verified"] = df_final["verified"].astype(int)

df_final

,created_at,description,entities,id,location,name,pinned_tweet_id,profile_image_url,protected,url,...,has_media,Cutoverdate,account_age_day,followers_following_ratio,tweets_per_day,description_length,url_ratio,hashtag_ratio,media_ratio,engagement_ratio
0,2020-01-16 02:02:55+00:00,Theoretical Computer Scientist. See also https...,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u1217628182611927040,"Cambridge, MA",Boaz Barak,NaN,https://pbs.twimg.com/profile_images/125226236...,False,https://t.co/BoMip9FF17,...,0,2022-03-16 00:00:00+00:00,789,33.870370,3.926489,92,0.000000,0.000000,0.000000,0.009020
1,2020-01-16 02:02:55+00:00,Theoretical Computer Scientist. See also https...,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u1217628182611927040,"Cambridge, MA",Boaz Barak,NaN,https://pbs.twimg.com/profile_images/125226236...,False,https://t.co/BoMip9FF17,...,1,2022-03-16 00:00:00+00:00,789,33.870370,3.926489,92,0.001613,0.000323,0.000323,0.110154
3,2012-02-21 19:25:01+00:00,"Husband, dad, poet, movie blogger, sports fan,...","{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u499091808,None,Dell on Movies,1.477858e+18,https://pbs.twimg.com/profile_images/130517574...,False,https://t.co/0C9nCXz8om,...,1,2022-03-16 00:00:00+00:00,3675,0.910814,6.831565,105,0.000080,0.000000,0.000040,0.050571
7,2020-07-23 16:49:48+00:00,her şeye rağmen yaşıyoruz,None,u1286342710157291520,المريخ,عبدالله,NaN,https://pbs.twimg.com/profile_images/131539468...,False,,...,0,2022-03-16 00:00:00+00:00,600,0.003686,0.170000,25,0.000000,0.000000,0.000000,12.000000
9,2008-06-23 20:59:59+00:00,"Director, Knowledge Ecology International, an ...","{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u15211869,"ÜT: 38.911326,-77.04508",James Love,1.335259e+18,https://pbs.twimg.com/profile_images/126138453...,False,https://t.co/mcNZxOR7gv,...,0,2022-03-16 00:00:00+00:00,5013,4.752653,11.449631,81,0.000000,0.000000,0.000000,0.000291
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
976346,2021-12-24 15:33:29+00:00,,None,u1474402819801337862,None,Bob,NaN,https://abs.twimg.com/sticky/default_profile_i...,False,,...,7,2022-03-16 00:00:00+00:00,81,0.091667,15.074074,0,0.000818,0.000818,0.005728,35.916667
976347,2017-05-25 07:50:58+00:00,,None,u867649175911100416,None,Tati Jewelry,NaN,https://pbs.twimg.com/profile_images/867651664...,False,,...,1,2022-03-16 00:00:00+00:00,1755,5.674952,226.084900,0,0.000003,0.000003,0.000003,0.079488
976348,2012-11-30 12:29:41+00:00,todos los dias on-line las 24hs por todos esto...,"{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u980374429,Ciudad Autónoma de Buenos Aire,TwitRadioo,9.012569e+17,https://pbs.twimg.com/profile_images/901249265...,False,https://t.co/KgoPxOXrUk,...,0,2022-03-16 00:00:00+00:00,3392,2.230588,28.959611,97,0.000020,0.000010,0.000000,0.007376
976349,2018-12-13 12:35:45+00:00,"Perpetual student of bioanalytical sciences, l...","{'url': {'urls': [{'start': 0, 'end': 23, 'url...",u1073194762407165952,None,SchejbalJan,NaN,https://pbs.twimg.com/profile_images/107319735...,False,https://t.co/S6e1ewGv2M,...,0,2022-03-16 00:00:00+00:00,1188,0.465625,0.882155,103,0.000953,0.000000,0.000000,0.086667
976350,2011-03-16 19:30:29+00:00,سناب خبر وعلم لنشر الوظائف الشاغرة والأخبار ال...,"{'description': {'urls': [{'start': 60, 'end':...",u267342787,المملكة العربية السعودية,خبر و عِلم,NaN,https://pbs.twimg.com/profile_images/148453887...,False,,...,9,2022-03-16 00:00:00+00:00,4017,31.709924,1.231267,83,0.000606,0.001011,0.001819,0.000241

In [ ]:
model_df = df_final[['label', 'tweet_count','followers_count', 'following_count',
       'followers_following_ratio', 'account_age_day', 'tweets_per_day',
       'verified', 'description_length', 'url_ratio', 'hashtag_ratio',
       'engagement_ratio'] ]

In [ ]:
from sklearn.utils import resample

# Separar por clase
df_bot = model_df[model_df["label"] == "bot"]
df_human = model_df[model_df["label"] == "human"]

print(f"Bots reales disponibles: {len(df_bot)}")
print(f"Humanos reales disponibles: {len(df_human)}")

# Tomamos TODOS los bots reales, sin resample ni duplicados
df_bot_final = df_bot.copy()

# Downsample de humanos para igualar la proporción deseada,
# usando la cantidad REAL de bots como referencia
n_bots = len(df_bot_final)
ratio_human_bot = 162436 / 37564
n_humans_target = int(n_bots * ratio_human_bot)

df_human_down = resample(
    df_human,
    replace=False,
    n_samples=min(n_humans_target, len(df_human)),  # nunca más de los que existen
    random_state=42
)

df_balanced = pd.concat([df_bot_final, df_human_down]).reset_index(drop=True)

print(f"\nDataset final: {len(df_balanced)} filas")
print(df_balanced["label"].value_counts(normalize=True))

In [ ]:
df_balanced

,label,tweet_count,followers_count,following_count,followers_following_ratio,account_age_day,tweets_per_day,verified,description_length,url_ratio,hashtag_ratio,engagement_ratio
535677,bot,919,189,583,0.323630,1814,0.506615,0,125,0.004348,0.004348,0.000000
33885,bot,3516,3063524,4,612704.800000,3325,1.057444,0,133,0.000000,0.000000,0.000496
403284,bot,7282,2677,285,9.360140,2440,2.984426,0,103,0.000137,0.000000,4.086258
241991,bot,97610,52226,9399,5.555957,5452,17.903522,0,136,0.000000,0.000010,0.000268
565365,bot,388,170,567,0.299296,4331,0.089587,0,160,0.000000,0.012853,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
157104,human,11052,5461,4076,1.339465,4808,2.298669,0,160,0.000090,0.000000,0.003295
302960,human,58867,23301,14060,1.657137,5098,11.547077,0,121,0.000085,0.000051,0.000129
21270,human,29865,338595,66,5053.656716,3521,8.481965,1,137,0.000067,0.000000,0.010257
61281,human,21593,15230,5938,2.564405,3642,5.928885,0,20,0.000046,0.000000,0.001182
228891,human,168050,13245,1035,12.784749,4397,38.219240,0,82,0.000012,0.000018,0.077457

In [ ]:
label_percentages = df_balanced['label'].value_counts(normalize=True) * 100
display(label_percentages)

label
human    81.218
bot      18.782
Name: proportion, dtype: float64

In [ ]:
label_percentages = model_df['label'].value_counts(normalize=True) * 100
display(label_percentages)

label
human    92.084224
bot       7.915776
Name: proportion, dtype: float64

In [ ]:
model_df.columns

Index(['label', 'tweet_count', 'followers_count', 'following_count',
       'followers_following_ratio', 'account_age_day', 'tweets_per_day',
       'verified', 'description_length', 'url_ratio', 'hashtag_ratio',
       'engagement_ratio'],
      dtype='object')

In [ ]:
model_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 474546 entries, 0 to 976350
Data columns (total 12 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   label                      474546 non-null  object
 1   tweet_count                474546 non-null  int64
 2   followers_count            474546 non-null  int64
 3   following_count            474546 non-null  int64
 4   followers_following_ratio  474546 non-null  float64
 5   account_age_day            474546 non-null  int64
 6   tweets_per_day             474546 non-null  float64
 7   verified                   474546 non-null  int64
 8   description_length         474546 non-null  int64
 9   url_ratio                  474546 non-null  float64
 10  hashtag_ratio              474546 non-null  float64
 11  engagement_ratio           474546 non-null  float64
dtypes: float64(5), int64(6), object(1)
memory usage: 47.1+ MB

In [ ]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X_res, y_res = smote.fit_resample(X, y)

In [ ]:
X

,tweet_count,followers_count,following_count,followers_following_ratio,account_age_day,tweets_per_day,verified,description_length,url_ratio,hashtag_ratio,engagement_ratio
535677,919,189,583,0.323630,1814,0.506615,0,125,0.004348,0.004348,0.000000
33885,3516,3063524,4,612704.800000,3325,1.057444,0,133,0.000000,0.000000,0.000496
403284,7282,2677,285,9.360140,2440,2.984426,0,103,0.000137,0.000000,4.086258
241991,97610,52226,9399,5.555957,5452,17.903522,0,136,0.000000,0.000010,0.000268
565365,388,170,567,0.299296,4331,0.089587,0,160,0.000000,0.012853,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
157104,11052,5461,4076,1.339465,4808,2.298669,0,160,0.000090,0.000000,0.003295
302960,58867,23301,14060,1.657137,5098,11.547077,0,121,0.000085,0.000051,0.000129
21270,29865,338595,66,5053.656716,3521,8.481965,1,137,0.000067,0.000000,0.010257
61281,21593,15230,5938,2.564405,3642,5.928885,0,20,0.000046,0.000000,0.001182
228891,168050,13245,1035,12.784749,4397,38.219240,0,82,0.000012,0.000018,0.077457

In [ ]:
X_res

,tweet_count,followers_count,following_count,followers_following_ratio,account_age_day,tweets_per_day,verified,description_length,url_ratio,hashtag_ratio,engagement_ratio
0,919,189,583,0.323630,1814,0.506615,0,125,0.004348,0.004348,0.000000
1,3516,3063524,4,612704.800000,3325,1.057444,0,133,0.000000,0.000000,0.000496
2,7282,2677,285,9.360140,2440,2.984426,0,103,0.000137,0.000000,4.086258
3,97610,52226,9399,5.555957,5452,17.903522,0,136,0.000000,0.000010,0.000268
4,388,170,567,0.299296,4331,0.089587,0,160,0.000000,0.012853,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
324867,4645,7119,7245,0.982502,1789,2.615908,0,87,0.000311,0.000057,0.007781
324868,44,8,7,1.888898,322,0.136081,0,156,0.016200,0.025348,0.082619
324869,1016,229,356,0.643128,145,7.355865,0,52,0.000000,0.001947,78.243243
324870,12485,4485,4856,0.924826,874,14.800862,0,159,0.000095,0.000047,0.002684
324871,9548,722,1470,0.490823,482,19.809129,0,76,0.000105,0.000000,0.008299

In [ ]:
y_res

0         1
1         1
2         1
3         1
4         1
         ..
324867    1
324868    1
324869    1
324870    1
324871    1
Name: label, Length: 324872, dtype: int64

In [ ]:
label_percentages = df_balanced['label'].value_counts(normalize=True) * 100
display(label_percentages)

# division de los datos

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    roc_auc_score,
    confusion_matrix,
    classification_report
)

In [ ]:
# Convertimos label a binaria
df_balanced['label'] = df_balanced['label'].map({'human': 0, 'bot': 1})

In [ ]:
#Separamos la variable objetivo
X = df_balanced.drop("label", axis=1)
y = df_balanced["label"]

In [ ]:
#División Train  y Test
#stratify=y mantiene el balance de clases.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
# Estandarizamos las variables con la función StandardScaler
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()

# Variables independientes entrenamiento estandarizadas
X_train = sc_x.fit_transform(X_train)
# Variables independientes testing estandarizadas
# Aquí ponemos transform únicamente para decirle que haga la misma transformación que
# hemos aplicado sobre el conjunto de entrenamiento
X_test = sc_x.transform(X_test)

# desbalanceado

Logistic regresion

In [ ]:
# utilizamos el modelo Logistic Regression

log_reg = LogisticRegression(
    max_iter=500,

    random_state=42
)

In [ ]:
#Elegimos la validación cruzada porque mantiene balance de clases y reduce varianza
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [ ]:
#Definimos los imperparametros
param_grid = {
    "C": [0.01, 0.1, 1, 10],
    "penalty": ["l1", "l2"],
    "solver": ["liblinear"]
}

In [ ]:
#Elimos los mejores parametros del modelo con GridSearchCV
grid_search = GridSearchCV(
    estimator=log_reg,
    param_grid=param_grid,
    scoring="f1",
    cv=cv,
    n_jobs=-1,
    verbose=2
)

In [ ]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=LogisticRegression(max_iter=500, random_state=42),
             n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10], 'penalty': ['l1', 'l2'],
                         'solver': ['liblinear']},
             scoring='f1', verbose=2)

In [ ]:
print("Mejores parámetros encontrados:")
print(grid_search.best_params_)

print("\nMejor f1 (CV):")
print(grid_search.best_score_)

Mejores parámetros encontrados:
{'C': 10, 'penalty': 'l1', 'solver': 'liblinear'}

Mejor f1 (CV):
0.2788357164042775

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print("\nMatriz de confusión:")
print(cm)

print("\nReporte de clasificación:")
print(classification_report(y_test, y_pred))

Matriz de confusión:
[[31767   720]
 [ 6193  1320]]

Reporte de clasificación:
              precision    recall  f1-score   support

           0       0.84      0.98      0.90     32487
           1       0.65      0.18      0.28      7513

    accuracy                           0.83     40000
   macro avg       0.74      0.58      0.59     40000
weighted avg       0.80      0.83      0.78     40000

In [ ]:
best_model = grid_search.best_estimator_

# Predicciones
y_pred = best_model.predict(X_test)
y_proba = best_model.predict_proba(X_test)[:, 1]

# Métrica ROC-AUC
roc_auc = roc_auc_score(y_test, y_proba)

print("\nROC-AUC en test:")
print(roc_auc)

ROC-AUC en test:
0.799983280537435

random forest

In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.metrics import classification_report, accuracy_score

In [ ]:
rf = RandomForestClassifier(random_state=42)

# =========================
# 3. Definir parámetros (Grid)
# =========================
param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [ 10, 20],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]
}

# =========================
# 4. Stratified K-Fold
# =========================
cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

# =========================
# 5. Grid Search
# =========================
grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=cv,
    scoring="f1",   # importante para datasets desbalanceados
    n_jobs=-1,
    verbose=2
)

grid_search.fit(X_train, y_train)

# =========================
# 6. Mejores resultados
# =========================
print("Mejores parámetros:", grid_search.best_params_)
print("Mejor score:", grid_search.best_score_)

# =========================
# 7. Evaluación final
# =========================
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Fitting 3 folds for each of 16 candidates, totalling 48 fits
Mejores parámetros: {'max_depth': 20, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
Mejor score: 0.6578042360669952

Accuracy: 0.90135

Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.97      0.94     32487
           1       0.81      0.62      0.70      7513

    accuracy                           0.90     40000
   macro avg       0.86      0.79      0.82     40000
weighted avg       0.90      0.90      0.90     40000

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print("\nMatriz de confusión:")
print(cm)

print("\nReporte de clasificación:")
print(classification_report(y_test, y_pred))

Matriz de confusión:
[[31397  1090]
 [ 2856  4657]]

Reporte de clasificación:
              precision    recall  f1-score   support

           0       0.92      0.97      0.94     32487
           1       0.81      0.62      0.70      7513

    accuracy                           0.90     40000
   macro avg       0.86      0.79      0.82     40000
weighted avg       0.90      0.90      0.90     40000

In [ ]:
best_model = grid_search.best_estimator_

# Predicciones
y_pred = best_model.predict(X_test)
y_proba = best_model.predict_proba(X_test)[:, 1]

# Métrica ROC-AUC
roc_auc = roc_auc_score(y_test, y_proba)

print("\nROC-AUC en test:")
print(roc_auc)

ROC-AUC en test:
0.9270806296287059

xgboost

In [ ]:
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import GridSearchCV, StratifiedKFold, train_test_split
from sklearn.metrics import classification_report, accuracy_score

# =========================
# 4. Modelo base
# =========================
xgb_model = xgb.XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,

)

# =========================
# 5. Grid de parámetros
# =========================
param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [4, 6, 10],
    "learning_rate": [0.05, 0.1],
    "subsample": [0.8, 1],
    "colsample_bytree": [0.8, 1]
}

# =========================
# 6. Stratified KFold
# =========================
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# =========================
# 7. Grid Search
# =========================
grid_search = GridSearchCV(
    estimator=xgb_model,
    param_grid=param_grid,
    cv=cv,
    scoring="f1",
    n_jobs=-1,
    verbose=2
)

grid_search.fit(X_train, y_train)

# =========================
# 8. Mejores parámetros
# =========================
print("Mejores parámetros:", grid_search.best_params_)
print("Mejor score:", grid_search.best_score_)

# =========================
# 9. Evaluación final
# =========================
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Fitting 5 folds for each of 48 candidates, totalling 240 fits
Mejores parámetros: {'colsample_bytree': 1, 'learning_rate': 0.1, 'max_depth': 10, 'n_estimators': 200, 'subsample': 0.8}
Mejor score: 0.6321028013672516

Accuracy: 0.883725

Classification Report:
               precision    recall  f1-score   support

           0       0.91      0.96      0.93     32487
           1       0.75      0.57      0.65      7513

    accuracy                           0.88     40000
   macro avg       0.83      0.76      0.79     40000
weighted avg       0.88      0.88      0.88     40000

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print("\nMatriz de confusión:")
print(cm)

print("\nReporte de clasificación:")
print(classification_report(y_test, y_pred))

Matriz de confusión:
[[31098  1389]
 [ 3262  4251]]

Reporte de clasificación:
              precision    recall  f1-score   support

           0       0.91      0.96      0.93     32487
           1       0.75      0.57      0.65      7513

    accuracy                           0.88     40000
   macro avg       0.83      0.76      0.79     40000
weighted avg       0.88      0.88      0.88     40000

In [ ]:
best_model = grid_search.best_estimator_

# Predicciones
y_pred = best_model.predict(X_test)
y_proba = best_model.predict_proba(X_test)[:, 1]

# Métrica ROC-AUC
roc_auc = roc_auc_score(y_test, y_proba)

print("\nROC-AUC en test:")
print(roc_auc)

ROC-AUC en test:
0.9152117983029557


# class_weight="balanced"

In [ ]:
# utilizamos el modelo Logistic Regression

log_reg = LogisticRegression(
    max_iter=500,
    class_weight="balanced",
    random_state=42
)

In [ ]:
#Elegimos la validación cruzada porque mantiene balance de clases y reduce varianza
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [ ]:
#Definimos los imperparametros
param_grid = {
    "C": [0.01, 0.1, 1, 10],
    "penalty": ["l1", "l2"],
    "solver": ["liblinear"]
}

In [ ]:
#Elimos los mejores parametros del modelo con GridSearchCV
grid_search = GridSearchCV(
    estimator=log_reg,
    param_grid=param_grid,
    scoring="f1",
    cv=cv,
    n_jobs=-1,
    verbose=2
)

In [ ]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=LogisticRegression(class_weight='balanced', max_iter=500,
                                          random_state=42),
             n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10], 'penalty': ['l1', 'l2'],
                         'solver': ['liblinear']},
             scoring='f1', verbose=2)

In [ ]:
print("Mejores parámetros encontrados:")
print(grid_search.best_params_)

print("\nMejor ROC-AUC (CV):")
print(grid_search.best_score_)

Mejores parámetros encontrados:
{'C': 10, 'penalty': 'l2', 'solver': 'liblinear'}

Mejor ROC-AUC (CV):
0.48056263223111617

In [ ]:
best_model = grid_search.best_estimator_

# Predicciones
y_pred = best_model.predict(X_test)
y_proba = best_model.predict_proba(X_test)[:, 1]

# Métrica ROC-AUC
roc_auc = roc_auc_score(y_test, y_proba)

print("\nROC-AUC en test:")
print(roc_auc)

ROC-AUC en test:
0.7984288146449644

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print("\nMatriz de confusión:")
print(cm)

print("\nReporte de clasificación:")
print(classification_report(y_test, y_pred))

Matriz de confusión:
[[21777 10710]
 [ 1717  5796]]

Reporte de clasificación:
              precision    recall  f1-score   support

           0       0.93      0.67      0.78     32487
           1       0.35      0.77      0.48      7513

    accuracy                           0.69     40000
   macro avg       0.64      0.72      0.63     40000
weighted avg       0.82      0.69      0.72     40000

randomforest

In [ ]:
rf = RandomForestClassifier(random_state=42,class_weight="balanced")

# =========================
# 3. Definir parámetros (Grid)
# =========================
param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [ 10, 20],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]
}

# =========================
# 4. Stratified K-Fold
# =========================
cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

# =========================
# 5. Grid Search
# =========================
grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=cv,
    scoring="f1",   # importante para datasets desbalanceados
    n_jobs=-1,
    verbose=2
)

grid_search.fit(X_train, y_train)

# =========================
# 6. Mejores resultados
# =========================
print("Mejores parámetros:", grid_search.best_params_)
print("Mejor score:", grid_search.best_score_)

# =========================
# 7. Evaluación final
# =========================
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

print("\nAccuracy:", accuracy_score(y_test, y_pred))

Fitting 3 folds for each of 16 candidates, totalling 48 fits
Mejores parámetros: {'max_depth': 20, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
Mejor score: 0.6881891045867515

Accuracy: 0.895275

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print("\nMatriz de confusión:")
print(cm)

print("\nReporte de clasificación:")
print(classification_report(y_test, y_pred))

Matriz de confusión:
[[30156  2331]
 [ 1858  5655]]

Reporte de clasificación:
              precision    recall  f1-score   support

           0       0.94      0.93      0.94     32487
           1       0.71      0.75      0.73      7513

    accuracy                           0.90     40000
   macro avg       0.83      0.84      0.83     40000
weighted avg       0.90      0.90      0.90     40000

In [ ]:
best_model = grid_search.best_estimator_

# Predicciones
y_pred = best_model.predict(X_test)
y_proba = best_model.predict_proba(X_test)[:, 1]

# Métrica ROC-AUC
roc_auc = roc_auc_score(y_test, y_proba)

print("\nROC-AUC en test:")
print(roc_auc)

ROC-AUC en test:
0.9307551686884094

XGBOOST

In [ ]:
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import GridSearchCV, StratifiedKFold, train_test_split
from sklearn.metrics import classification_report, accuracy_score

# =========================
# 3. Manejo del desbalance
# =========================
scale_pos_weight = (y_train == 0).sum() / (y_train == 1).sum()

# =========================
# 4. Modelo base
# =========================
xgb_model = xgb.XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,
    scale_pos_weight=scale_pos_weight

)

# =========================
# 5. Grid de parámetros
# =========================
param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [4, 6, 10],
    "learning_rate": [0.05, 0.1],
    "subsample": [0.8, 1],
    "colsample_bytree": [0.8, 1]
}

# =========================
# 6. Stratified KFold
# =========================
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# =========================
# 7. Grid Search
# =========================
grid_search = GridSearchCV(
    estimator=xgb_model,
    param_grid=param_grid,
    cv=cv,
    scoring="f1",
    n_jobs=-1,
    verbose=2
)

grid_search.fit(X_train, y_train)

# =========================
# 8. Mejores parámetros
# =========================
print("Mejores parámetros:", grid_search.best_params_)
print("Mejor score:", grid_search.best_score_)

# =========================
# 9. Evaluación final
# =========================
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

print("\nAccuracy:", accuracy_score(y_test, y_pred))

Fitting 5 folds for each of 48 candidates, totalling 240 fits
Mejores parámetros: {'colsample_bytree': 1, 'learning_rate': 0.1, 'max_depth': 10, 'n_estimators': 200, 'subsample': 0.8}
Mejor score: 0.6741658223218063

Accuracy: 0.859425

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print("\nMatriz de confusión:")
print(cm)

print("\nReporte de clasificación:")
print(classification_report(y_test, y_pred))

Matriz de confusión:
[[28185  4302]
 [ 1321  6192]]

Reporte de clasificación:
              precision    recall  f1-score   support

           0       0.96      0.87      0.91     32487
           1       0.59      0.82      0.69      7513

    accuracy                           0.86     40000
   macro avg       0.77      0.85      0.80     40000
weighted avg       0.89      0.86      0.87     40000

In [ ]:
best_model = grid_search.best_estimator_

# Predicciones
y_pred = best_model.predict(X_test)
y_proba = best_model.predict_proba(X_test)[:, 1]

# Métrica ROC-AUC
roc_auc = roc_auc_score(y_test, y_proba)

print("\nROC-AUC en test:")
print(roc_auc)

ROC-AUC en test:
0.9192017037594507

# Smote

In [ ]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV, StratifiedKFold
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import (
    roc_auc_score,
    confusion_matrix,
    classification_report
)

In [ ]:
# Convertimos label a binaria
df_balanced['label'] = df_balanced['label'].map({'human': 0, 'bot': 1})

In [ ]:
#Separamos la variable objetivo
X = df_balanced.drop("label", axis=1)
y = df_balanced["label"]

In [ ]:
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
X, y = smote.fit_resample(X, y)

In [ ]:
#División Train  y Test
#stratify=y mantiene el balance de clases.
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [ ]:
# Estandarizamos las variables con la función StandardScaler
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()

# Variables independientes entrenamiento estandarizadas
X_train = sc_x.fit_transform(X_train)
# Variables independientes testing estandarizadas
# Aquí ponemos transform únicamente para decirle que haga la misma transformación que
# hemos aplicado sobre el conjunto de entrenamiento
X_test = sc_x.transform(X_test)

In [ ]:
# utilizamos el modelo Logistic Regression

log_reg = LogisticRegression(
    max_iter=500,

    random_state=42
)

In [ ]:
#Elegimos la validación cruzada porque mantiene balance de clases y reduce varianza
cv = StratifiedKFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)

In [ ]:
#Definimos los imperparametros
param_grid = {
    "C": [0.01, 0.1, 1, 10],
    "penalty": ["l1", "l2"],
    "solver": ["liblinear"]
}

In [ ]:
#Elimos los mejores parametros del modelo con GridSearchCV
grid_search = GridSearchCV(
    estimator=log_reg,
    param_grid=param_grid,
    scoring="f1",
    cv=cv,
    n_jobs=-1,
    verbose=2
)

In [ ]:
grid_search.fit(X_train, y_train)

Fitting 5 folds for each of 8 candidates, totalling 40 fits

GridSearchCV(cv=StratifiedKFold(n_splits=5, random_state=42, shuffle=True),
             estimator=LogisticRegression(max_iter=500, random_state=42),
             n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10], 'penalty': ['l1', 'l2'],
                         'solver': ['liblinear']},
             scoring='f1', verbose=2)

In [ ]:
print("Mejores parámetros encontrados:")
print(grid_search.best_params_)

print("\nMejor f1 (CV):")
print(grid_search.best_score_)

Mejores parámetros encontrados:
{'C': 10, 'penalty': 'l2', 'solver': 'liblinear'}

Mejor f1 (CV):
0.7361149192389767

In [ ]:
best_model = grid_search.best_estimator_

# Predicciones
y_pred = best_model.predict(X_test)
y_proba = best_model.predict_proba(X_test)[:, 1]

# Métrica ROC-AUC
roc_auc = roc_auc_score(y_test, y_proba)

print("\nROC-AUC en test:")
print(roc_auc)

ROC-AUC en test:
0.8013948461963916

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print("\nMatriz de confusión:")
print(cm)

print("\nReporte de clasificación:")
print(classification_report(y_test, y_pred))

Matriz de confusión:
[[22006 10482]
 [ 7336 25151]]

Reporte de clasificación:
              precision    recall  f1-score   support

           0       0.75      0.68      0.71     32488
           1       0.71      0.77      0.74     32487

    accuracy                           0.73     64975
   macro avg       0.73      0.73      0.73     64975
weighted avg       0.73      0.73      0.73     64975

Random forest

In [ ]:
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.metrics import classification_report, accuracy_score

In [ ]:
rf = RandomForestClassifier(random_state=42,class_weight="balanced")

# =========================
# 3. Definir parámetros (Grid)
# =========================
param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [ 10, 20],
    "min_samples_split": [2, 5],
    "min_samples_leaf": [1, 2]
}

# =========================
# 4. Stratified K-Fold
# =========================
cv = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

# =========================
# 5. Grid Search
# =========================
grid_search = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=cv,
    scoring="f1",   # importante para datasets desbalanceados
    n_jobs=-1,
    verbose=2
)

grid_search.fit(X_train, y_train)

# =========================
# 6. Mejores resultados
# =========================
print("Mejores parámetros:", grid_search.best_params_)
print("Mejor score:", grid_search.best_score_)

# =========================
# 7. Evaluación final
# =========================
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

print("\nAccuracy:", accuracy_score(y_test, y_pred))

Fitting 3 folds for each of 16 candidates, totalling 48 fits

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Mejores parámetros: {'max_depth': 20, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 200}
Mejor score: 0.890583894829284

Accuracy: 0.8983455175067333

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print("\nMatriz de confusión:")
print(cm)

print("\nReporte de clasificación:")
print(classification_report(y_test, y_pred))

Matriz de confusión:
[[28444  4044]
 [ 2561 29926]]

Reporte de clasificación:
              precision    recall  f1-score   support

           0       0.92      0.88      0.90     32488
           1       0.88      0.92      0.90     32487

    accuracy                           0.90     64975
   macro avg       0.90      0.90      0.90     64975
weighted avg       0.90      0.90      0.90     64975

In [ ]:
best_model = grid_search.best_estimator_

# Predicciones
y_pred = best_model.predict(X_test)
y_proba = best_model.predict_proba(X_test)[:, 1]

# Métrica ROC-AUC
roc_auc = roc_auc_score(y_test, y_proba)

print("\nROC-AUC en test:")
print(roc_auc)

ROC-AUC en test:
0.962323750935034

XGBOOST

In [ ]:
import pandas as pd
import xgboost as xgb
from sklearn.model_selection import GridSearchCV, StratifiedKFold, train_test_split
from sklearn.metrics import classification_report, accuracy_score

# =========================
# 4. Modelo base
# =========================
xgb_model = xgb.XGBClassifier(
    objective="binary:logistic",
    eval_metric="logloss",
    random_state=42,

)

# =========================
# 5. Grid de parámetros
# =========================
param_grid = {
    "n_estimators": [100, 200],
    "max_depth": [4, 6, 10],
    "learning_rate": [0.05, 0.1],
    "subsample": [0.8, 1],
    "colsample_bytree": [0.8, 1]
}

# =========================
# 6. Stratified KFold
# =========================
cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

# =========================
# 7. Grid Search
# =========================
grid_search = GridSearchCV(
    estimator=xgb_model,
    param_grid=param_grid,
    cv=cv,
    scoring="f1",
    n_jobs=-1,
    verbose=2
)

grid_search.fit(X_train, y_train)

# =========================
# 8. Mejores parámetros
# =========================
print("Mejores parámetros:", grid_search.best_params_)
print("Mejor score:", grid_search.best_score_)

# =========================
# 9. Evaluación final
# =========================
best_model = grid_search.best_estimator_
y_pred = best_model.predict(X_test)

print("\nAccuracy:", accuracy_score(y_test, y_pred))

Fitting 5 folds for each of 48 candidates, totalling 240 fits
Mejores parámetros: {'colsample_bytree': 1, 'learning_rate': 0.1, 'max_depth': 10, 'n_estimators': 200, 'subsample': 0.8}
Mejor score: 0.8809510627161716

Accuracy: 0.8824932666410158

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print("\nMatriz de confusión:")
print(cm)

print("\nReporte de clasificación:")
print(classification_report(y_test, y_pred))

Matriz de confusión:
[[28018  4470]
 [ 3165 29322]]

Reporte de clasificación:
              precision    recall  f1-score   support

           0       0.90      0.86      0.88     32488
           1       0.87      0.90      0.88     32487

    accuracy                           0.88     64975
   macro avg       0.88      0.88      0.88     64975
weighted avg       0.88      0.88      0.88     64975

In [ ]:
best_model = grid_search.best_estimator_

# Predicciones
y_pred = best_model.predict(X_test)
y_proba = best_model.predict_proba(X_test)[:, 1]

# Métrica ROC-AUC
roc_auc = roc_auc_score(y_test, y_proba)

print("\nROC-AUC en test:")
print(roc_auc)

ROC-AUC en test:
0.9509980895546141